
services:
  rails-web:
    build:
      context: ./marketBack
      dockerfile: Dockerfile
    command: bash -lc "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      KAFKA_BROKERS: "127.0.0.1:9092"
      CASSANDRA_HOSTS: cassandra-db
    networks:
      - arq_net

  rails-karafka:
    build:
      context: ./marketBack
      dockerfile: Dockerfile
    command: bash -lc "bundle exec karafka server"
    environment:
      RAILS_ENV: development
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://upbeat_wu:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      CASSANDRA_HOSTS: cassandra-db
    depends_on:
      - rails-web
    networks:
      - arq_net
      
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: apache/kafka:latest
    container_name: upbeat_wu
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092
      - ALLOW_PLAINTEXT_LISTENER=yes

networks:
   arq_net:
    external: true